---
- name: "Preflight is complete"
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: "Variables for operating system are defined"
  ansible.builtin.include_vars: "{{ distrovars }}"
  vars:
    distrovars: "{{ lookup('first_found', lookup_vars) }}"
    lookup_vars:
      files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "vars"
      skip: true

- name: "Set address"
  ansible.builtin.set_fact:
    ovn_addr: >-
      {{ ansible_facts.all_ipv4_addresses
      | select('ansible.utils.in_any_network', ovn_mgmt_cidr)
      | ansible.builtin.first }}
  when: ovn_addr is not defined

- name: "Default variables are combined"
  block:
    - name: "OVN controller variables are merged"
      ansible.builtin.set_fact:
        ovn_central_conf: "{{ ovn_central_conf_default | ansible.builtin.combine(ovn_central_conf | default({}), recursive=true) }}"
    - name: "OVN host variables are merged"
      ansible.builtin.set_fact:
        ovn_host_conf: "{{ ovn_host_conf_default | ansible.builtin.combine(ovn_host_conf | default({}), recursive=true) }}"

- name: "Controller components for OVN are installed"
  ansible.builtin.include_tasks:
    file: controller.yml
    apply:
      become: true
  when: ovn_is_controller | default(false) | bool

- name: "Host components for OVN are installed"
  ansible.builtin.include_tasks:
    file: node.yml
    apply:
      become: true
  when: ovn_is_node | default(false) | bool
