---
- name: "Host components for OVN are installed"
  ansible.builtin.package:
    name: "{{ ovn_host_package }}"
    state: "{{ (ovn_version != 'latest') | ansible.builtin.ternary('present', 'latest') }}"

- name: "Ovn-host parameters file is generated"
  ansible.builtin.template:
    src: "templates/ovn-host.j2"
    dest: "/etc/default/ovn-host"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Enable ovn-host service

- name: "Metadata for OVN-Controller is set"
  ovsdb-externalids:
    remote: "unix:/var/run/openvswitch/db.sock"
    ext_ids:
      - "ovn-remote={{ __ovn_sb_connection }}"
      - "ovn-encap-type=geneve"
      - "ovn-encap-ip={{ ovn_addr }}"
  become: true
